PRJ: Added validation data to Diaz cases in polydisperseBubbleFoam

diff --git a/validation/polydisperseBubbleFoam/Diaz/Diaz_1_2/validation/createGraph b/validation/polydisperseBubbleFoam/Diaz/Diaz_1_2/validation/createGraph
--- a/validation/polydisperseBubbleFoam/Diaz/Diaz_1_2/validation/createGraph
+++ b/validation/polydisperseBubbleFoam/Diaz/Diaz_1_2/validation/createGraph
@@ -1,5 +1,5 @@
 #!/bin/bash
-#
+
 createEps()
 {
     gnuplot<<EOF
@@ -7,7 +7,7 @@ createEps()
 
     set terminal postscript eps enhanced color font 'Helvetica,60' linewidth 2\
         dl 8.0
-    set output "Diaz3_2_4_p.eps"
+    set output "Diaz3_1_2_p.eps"
     set xlabel "Time [s]"
     set ylabel "Normalized Pressure"
     set datafile commentschars "#"
@@ -16,8 +16,8 @@ createEps()
     set size 2,2
     set autoscale
     set xrange [0:50]
-    set yrange [-20:20]
-    set key left top Left box
+    set yrange [-10:10]
+    set key top left Left box
 
     plot    "$2" using 1:2 title 'Diaz'\
                 with points pointtype 7 ps 2 linecolor rgb 'black', \
@@ -26,15 +26,20 @@ createEps()
 EOF
 }
 
+# test if gnuplot exists on the system
+if ! which gnuplot > /dev/null 2>&1
+then
+    echo "gnuplot not found - skipping graph creation" >&2
+    exit 1
+fi
+
 #set case Direcory names
-caseDir=$(pwd)
-pProbesDir="$caseDir/postProcessing/pProbes"
-validationDir="$caseDir/../validation/experiments"
+pProbesDir="../postProcessing/pProbes"
 
 #Set files
 pProbes_modified="$pProbesDir/0/p_rgh_modified"
 touch $pProbes_modified
-exp="$validationDir/experiments_1_2_data"
+exp="experiments_1_2.data"
 
 for d in $(ls $pProbesDir | sort -g);
 do
@@ -61,4 +66,3 @@ rm $pProbesTmp
 createEps $pProbesFinal $exp $1
 
 printf "\nDone\n"
-
